name: CraigSwann
favicon: null
layout_spectrum: 0.3349966856185347
typography_spectrum: 0.07706093
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff8'
    - '#000000'
    - '#808080'
    - '#a7a7a4'
    - '#585856'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
